# Generated by Django 5.1.1 on 2024-11-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medapp', '0003_patientdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='patient_name',
            field=models.CharField(default='Unknown Patient', max_length=100),
        ),
    ]
